export enum AnalysisStatus {
  NotStarted = "not_started",
  ReadyForAiAnalysis = "ready_for_ai_analysis",
  ReadyForSocialMedia = "ready_for_social_media",
  Complete = "complete",
}

export const RSS_FEEDS = [
  // "http://feeds.bbci.co.uk/news/rss.xml",
  "http://rss.cnn.com/rss/cnn_latest.rss",
  // "http://rss.cnn.com/rss/cnn_allpolitics.rss",
  // "http://rss.cnn.com/rss/cnn_topstories.rss",
  // "http://rss.cnn.com/rss/cnn_health.rss",
  // "http://rss.cnn.com/rss/cnn_tech.rss",
  // "http://rss.cnn.com/rss/cnn_world.rss",
  // "http://rss.cnn.com/rss/cnn_us.rss",
  "http://rss.cnn.com/rss/money_latest.rss",
  "https://moxie.foxnews.com/google-publisher/latest.xml",
  // "https://moxie.foxnews.com/google-publisher/politics.xml",
  // "https://moxie.foxnews.com/google-publisher/opinion.xml",
  // "https://moxie.foxnews.com/google-publisher/tech.xml",
  // "https://moxie.foxnews.com/google-publisher/world.xml",
  // "https://moxie.foxnews.com/google-publisher/health.xml",
  // "https://moxie.foxnews.com/google-publisher/science.xml",
  "https://feeds.nbcnews.com/nbcnews/public/news",
  // "https://www.cnbc.com/id/100727362/device/rss/rss.html",
  // "https://www.aljazeera.com/xml/rss/all.xml",
  // "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/section/world/rss.xml",
  "https://globalnews.ca/world/feed/",
  // "https://feeds.feedburner.com/time/world",
  // "https://feeds.npr.org/1004/rss.xml",
  // "https://www.washingtontimes.com/rss/headlines/news/world",
  // "https://www.smh.com.au/rss/world.xml",
  "https://feeds.skynews.com/feeds/rss/world.xml",
  // "https://www.latimes.com/world-nation/rss2.0.xml#nt=1col-7030col1",
  // "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms",
  // "https://www.rt.com/rss/news/",
  // "https://www.globalissues.org/news/feed",
  // "https://defence-blog.com/feed/",
  // "https://www.thesun.co.uk/news/worldnews/feed/",
  // "https://www.usnn.news/feed/",
  // "http://worldunitednews.blogspot.com/feeds/posts/default",
  // "https://www.scmp.com/rss/91/feed/",
  // "https://www.theguardian.com/world/rss",
  // "https://rightwirereport.com/feed/",
  // "http://asiandefencenewschannel.blogspot.com/feeds/posts/default",
  "https://allworldnews24hours6.blogspot.com/feeds/posts/default",
];
